export const START_GAME = "START_GAME";
export const CHANGE_FIELD_SIZE = "CHANGE_FIELD_SIZE";
export const CHANGE_MINES_COUNT = "CHANGE_MINES_COUNT";
export const REVEAL_TILE = "REVEAL_TILE";
export const TOGGLE_FLAGGED_TILE = "TOGGLE_FLAGGED_TILE";
